//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bio
    {
        public int BioID { get; set; }
        public string Başlık { get; set; }
        public string Resim { get; set; }
        public string Bio1 { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string İnstagram { get; set; }
        public string Linkedin { get; set; }
    }
}
