//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blog1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class postlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postlar()
        {
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int PostID { get; set; }
        public int YazarID { get; set; }
        public int KategoriID { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Görüntülenme { get; set; }
        public string Başlık { get; set; }
        public string Foto { get; set; }
        public string İçerikÖzet { get; set; }
        public string İçerik { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
